import matplotlib.pyplot as plt
import matplotlib.animation as animation
from netCDF4 import Dataset

# animate data from netcdf file generated by sqg_run.py

filename = 'sqg_enkf_N128_N64_3hrly_blockmean1.nc'
vmin = -8.; vmax = 8.; levplot = 1

nc = Dataset(filename)
pv_b = nc['pv_b']
pv_a = nc['pv_a']
t_var = nc['t']
nsteps = len(t_var)-1

fig = plt.figure(figsize=(8,8))
fig.subplots_adjust(left=0, bottom=0.0, top=1., right=1.)
nout = 1

def initfig():
    global im
    ax = fig.add_subplot(111)
    ax.axis('off')
    pv = pv_b[0,levplot,...]-pv_a[0,levplot,...]
    im = ax.imshow(pv,cmap=plt.cm.bwr,interpolation='nearest',origin='lower',vmin=vmin,vmax=vmax)
    return im,

def updatefig(*args):
    global nout
    t = t_var[nout]
    pv = pv_b[nout]-pv_a[nout]
    hr = t/3600.
    print hr,pv.min(),pv.max()
    im.set_data(pv[levplot])
    nout += 1
    return im,

# interval=0 means draw as fast as possible
ani = animation.FuncAnimation(fig, updatefig, frames=nsteps, repeat=False,\
      init_func=initfig,interval=0,blit=True)
plt.show()
